import { NextRequest, NextResponse } from "next/server";
import { requireAdminApiRole } from "@/lib/admin-api-auth";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { normalizeAnchorText } from "@/lib/search/anchors/normalize";
import { SEARCH_ANCHOR_DETAIL_FIELDS, sanitizeSearchAnchorPayload } from "@/lib/admin/search-security-projections";
const roles = ["superadmin", "admin", "manager"] as const;
export async function GET(_: NextRequest, ctx: { params: Promise<{ id: string }> }) { const auth = await requireAdminApiRole(roles); if (auth.error) return auth.error; const { id } = await ctx.params; const { data, error } = await supabaseAdmin.from("search_anchors").select(SEARCH_ANCHOR_DETAIL_FIELDS).eq("id", id).single(); return error ? NextResponse.json({ success:false,error:error.message},{status:404}) : NextResponse.json({ success:true, anchor:data }); }
export async function PATCH(req: NextRequest, ctx: { params: Promise<{ id: string }> }) { const auth = await requireAdminApiRole(roles); if (auth.error) return auth.error; const { id } = await ctx.params; const payload = sanitizeSearchAnchorPayload(await req.json().catch(()=>({}))); if (typeof payload.canonical_name === "string") payload.normalized_name=normalizeAnchorText(payload.canonical_name); if (!Object.keys(payload).length) return NextResponse.json({success:false,error:"No supported fields supplied"},{status:400}); const { data,error } = await supabaseAdmin.from("search_anchors").update(payload).eq("id",id).select(SEARCH_ANCHOR_DETAIL_FIELDS).single(); return error ? NextResponse.json({success:false,error:error.message},{status:400}) : NextResponse.json({success:true,anchor:data}); }
export async function DELETE(_: NextRequest, ctx: { params: Promise<{ id: string }> }) { const auth = await requireAdminApiRole(roles); if (auth.error) return auth.error; const { id } = await ctx.params; const { data: anchor } = await supabaseAdmin.from("search_anchors").select("usage_count,successful_search_count,no_result_count").eq("id", id).single(); if (Number(anchor?.usage_count ?? 0) > 0) { const { error } = await supabaseAdmin.from("search_anchors").update({ is_active:false,is_searchable:false,review_status:"disabled" }).eq("id",id); return NextResponse.json({success:!error, soft_deleted:true, error:error?.message}); } const { error } = await supabaseAdmin.from("search_anchors").delete().eq("id", id); return NextResponse.json({ success: !error, error: error?.message }); }
